import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AccentInitializer } from "@/utils/accentInitializer";
import localFont from "next/font/local";
import { BackgroundInitializer } from "@/utils/backgroundInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const auro = localFont({
  src: [
    { path: "../public/fonts/Auro-Light.otf", weight: "200", style: "normal" },
    {
      path: "../public/fonts/Auro-Light Italic.otf",
      weight: "200",
      style: "italic",
    },
    { path: "../public/fonts/Auro-Book.otf", weight: "300", style: "normal" },
    {
      path: "../public/fonts/Auro-Book Italic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/Auro-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Auro-Regular Italic.otf",
      weight: "400",
      style: "italic",
    },
    { path: "../public/fonts/Auro-Medium.otf", weight: "500", style: "normal" },
    {
      path: "../public/fonts/Auro-Medium Italic.otf",
      weight: "500",
      style: "italic",
    },
    { path: "../public/fonts/Auro-Bold.otf", weight: "700", style: "normal" },
    {
      path: "../public/fonts/Auro-Bold Italic.otf",
      weight: "700",
      style: "italic",
    },
    { path: "../public/fonts/Auro-Black.otf", weight: "900", style: "normal" },
    {
      path: "../public/fonts/Auro-Black Italic.otf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-auro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${auro.variable} antialiased`}>
        <AccentInitializer />
        <BackgroundInitializer />
        {children}
      </body>
    </html>
  );
}
